-- Execute este arquivo no Supabase > SQL Editor.
-- Ele cria as tabelas e garante que cada usuário só consiga ler/alterar os próprios dados.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  closing_day integer not null default 5 check (closing_day between 1 and 28),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('income','expense')),
  name text not null,
  amount numeric(12,2) not null check (amount >= 0),
  category text,
  entry_date date not null default current_date,
  confirmed boolean not null default true,
  is_fixed boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists entries_user_date_idx on public.entries(user_id, entry_date);

create table if not exists public.month_closings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  period text not null check (period ~ '^\\d{4}-\\d{2}$'),
  total_income numeric(12,2) not null default 0,
  total_expense numeric(12,2) not null default 0,
  balance numeric(12,2) not null default 0,
  closed_at timestamptz not null default now(),
  unique(user_id, period)
);

alter table public.profiles enable row level security;
alter table public.entries enable row level security;
alter table public.month_closings enable row level security;

-- profiles
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "profiles_delete_own" on public.profiles for delete using (auth.uid() = id);

-- entries
create policy "entries_select_own" on public.entries for select using (auth.uid() = user_id);
create policy "entries_insert_own" on public.entries for insert with check (auth.uid() = user_id);
create policy "entries_update_own" on public.entries for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "entries_delete_own" on public.entries for delete using (auth.uid() = user_id);

-- month_closings
create policy "closings_select_own" on public.month_closings for select using (auth.uid() = user_id);
create policy "closings_insert_own" on public.month_closings for insert with check (auth.uid() = user_id);
create policy "closings_update_own" on public.month_closings for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "closings_delete_own" on public.month_closings for delete using (auth.uid() = user_id);
